server:
  port: 8181

spring:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  datasource:
    url: jdbc:postgresql://localhost:5432/dataBase
    username: admin
    password: 1234